algorithm:
  policy: SimplePolicy
  policy_kwargs:
    features_extractor_class: StateExtractor
    features_extractor_kwargs:
      net_arch:
        state:
          layer: [128, 64]
       
    critic:
      dist: mse
      n_critics: 1
      net_arch:
        layer: [128, 64]
    actor:
      dist: normal
      net_arch:
        layer: [128, 64]

    activation_fn: relu
    optimizer_class: adam
    optimizer_kwargs:
      weight_decay: 0.00001
    
  learning_rate: 0.002
  horizon: 64
  tau: 0.005
  gamma: 0.98
  batch_size: 256
  train_freq: 64
  gradient_steps: 10
  actor_gradient_steps: 1
  device: cpu

# Environment overrides for BPTT
env_overrides:
  requires_grad: true
  tensor_output: false
  device: cpu
  num_agent_per_scene: 80

# Learning parameters
learn:
  total_timesteps: 15000
  log_interval: 1

# Test parameters
test:
  is_fig: true
  is_fig_save: true
  is_video: true 
  is_video_save: true
  render_kwargs: {}