algorithm:
  policy: CustomMultiInputPolicy
  policy_kwargs:
    features_extractor_class: FlexibleExtractor
    features_extractor_kwargs:
      net_arch:
        depth:
          layer: [128, 64]
        semantic:
          layer: [128, 64]
        state:
          layer: [128, 64]
    net_arch:
      pi: [64, 64]
      vf: [64, 64]
    optimizer_kwargs:
      weight_decay: 0.00001
    share_features_extractor: false
  
  learning_rate: 0.001
  device: cpu
  gamma: 0.99
  gae_lambda: 0.95
  n_epochs: 10
  n_steps: 256
  batch_size: 1024
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  clip_range: 0.2
  verbose: 1

# Learning parameters
learn:
  total_timesteps: 51200
  log_interval: 1

# Test parameters
test:
  is_fig: true
  is_fig_save: true
  is_video: true
  is_video_save: true
  render_kwargs: {}