algorithm:
  policy: SimplePolicy
  policy_kwargs:
    features_extractor_class: FlexibleExtractor
    features_extractor_kwargs:
      net_arch:
        state:
          layer: [128, 64]
        color:
          layer: [256, 128]
        target:
          layer: [32, 16]
       
    critic:
      dist: mse
      n_critics: 1
      net_arch:
        layer: [128, 64]
    actor:
      dist: normal
      net_arch:
        layer: [128, 64]

    activation_fn: relu
    optimizer_class: adam
    optimizer_kwargs:
      weight_decay: 0.00001

  learning_rate: 0.005
  horizon: 96
  tau: 0.005
  gamma: 0.99
  batch_size: 25600
  train_freq: 96
  gradient_steps: 10
  actor_gradient_steps: 1
  device: cuda


# Learning/training parameters
learn:
  total_timesteps: 5000
  log_interval: 20

# Test parameters (for evaluation mode)
test:
  is_fig: True
  is_fig_save: True
  is_video: True
  is_video_save: True
  render_kwargs: {}