algorithm:
  policy: MultiInputPolicy
  policy_kwargs:
    features_extractor_class: FlexibleExtractor
    features_extractor_kwargs:
      net_arch:
        depth:
          layer: [256, 128]
        rgb:
          layer: [128, 64]
        state:
          layer: [128, 64]
      activation_fn: relu
    net_arch:
      pi: [128, 128, 64]
      qf: [128, 128, 64]
    activation_fn: relu
    optimizer_kwargs:
      weight_decay: 0.00001
  
  learning_rate: 0.0005
  horizon: 100
  tau: 0.005
  gamma: 0.997
  gradient_steps: 10
  buffer_size: 1500000
  batch_size: 300000
  device: cpu

# Environment overrides for SHAC
env_overrides:
  requires_grad: true
  tensor_output: false
  device: cpu
  num_agent_per_scene: 40

# Learning parameters
learn:
  total_timesteps: 120000
  log_interval: 1

# Test parameters
test:
  is_fig: true
  is_fig_save: true
  is_video: true
  is_video_save: true
  render_kwargs: {}