# Navigation task configuration

task:
  name: "drone_hover"
  category: "hover"
  
  # Task description for LLM
  description: >
    Hover drone to target position efficiently.
    
    The drone must:
    1. Reach the target position with high precision
    2. Maintain stable flight dynamics