# Navigation task configuration

task:
  name: "drone_navigation"
  category: "navigation"
  
  # Task description for LLM
  description: >
    Navigate drone to target position efficiently while avoiding obstacles.
    
    The drone must:
    1. Reach the target position with high precision (within 0.5m)
    2. Avoid collisions using depth sensor data 
    3. Maintain stable flight dynamics
    4. Minimize episode length for efficiency
    5. Handle multiple agents simultaneously
    
    Reward function should:
    - Use distance-based rewards for navigation
    - Incorporate depth sensor for obstacle avoidance
    - Penalize unstable flight (high angular velocities)
    - Provide shaping rewards for smooth trajectories
    - Balance multiple objectives appropriately

  # Training configuration
  training:
    algorithm: "${optimization.algorithm}"
    steps_per_evaluation: 50
    evaluation_episodes: 20
    success_threshold: 0.8
    
  # Reward function constraints
  reward_constraints:
    max_components: 8         # Maximum reward components
    numerical_stability: true # Ensure numerical stability
    differentiable: true      # Must be differentiable for BPTT
    
  # Evaluation metrics
  metrics:
    primary: "success_rate"   # Primary optimization metric
    secondary: 
      - "episode_length"
      - "collision_rate" 
      - "energy_efficiency"
      - "trajectory_smoothness"