# PPO configuration for flip environment
# Uses custom multi-input observation

algorithm:
  policy: CustomMultiInputPolicy
  policy_kwargs:
    features_extractor_class: StateExtractor
    features_extractor_kwargs:
      net_arch:
        state:
          layer: [512]
        flip_progress:
          layer: [32]
    net_arch:
      pi: [512, 512]
      vf: [512, 512]
    optimizer_kwargs:
      weight_decay: 0.00001
    share_features_extractor: false

  learning_rate: 0.0003
  device: cuda
  gamma: 0.99
  gae_lambda: 0.95
  n_epochs: 10
  n_steps: 2048
  batch_size: 64
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  clip_range: 0.2
  verbose: 1

  # PPO specific
  use_sde: false
  sde_sample_freq: -1

# Learning parameters
learn:
  total_timesteps: 1000000
  log_interval: 10

# Test parameters
test:
  is_fig: true
  is_fig_save: true
  is_video: true
  is_video_save: true
  render_kwargs: {}